### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by X88Y** [3xepy/reghub#1]
Можно пожалуйста более подробную инструкцию . Я установил selenium но у меня появляется ошибка,  можно более подробно что делать с файлами. Заранее спасибо

**Comment by 3xepy** [comment]
Пожалуйста, напишите свою ошибку и версию Python!

**Comment by Tem4ik74** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\artem\Desktop\reghub-master\main.py", line 20, in main
    driver = webdriver.Firefox()
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\artem\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
Версия- 3.8, спасибо!
